### ISSUE TITLE
just some questions

### ISSUE THREAD

**Issue by lenscas** [Diggsey/rnet#1]
1. Is there a way to expose a struct to .NET where one of the fields does not implement the required traits? I'm not planning to make this field visible in the .NET side. I suppose I can make a global hashmap to store these fields and have these structs contain keys to index said map but I wonder if there is a better way to do this?

2. Is there a way to make functions that can accept any .NET type? I tried using generics but the macros didn't seem to like them.

3. Would you be open to a PR that adds the ability to generate another language than just C#? (F# to be precise). It isn't a huge deal if not as I can just make the C# file its own library but it would reduce some boilerplate and would make the functions nicer to call.

For a bit of context: I have a rust [library](https://github.com/lenscas/tealr) which I want to expose to one of my F# projects. I'm currently in the "toying around/experiment" phase though.

**Comment by Diggsey** [comment]
Hi @lenscas,

1. Not at the moment. Currently `derive(Net)` requires conversion in both directions to work, so it's not possible to omit fields like that, but it's something I may add in future.

2. No, although even if you could, the code wouldn't be able to do much beyond send it back. This might not be too hard to add support for if you want to open a PR. It would basically involve storing a `Dictionary<Id, object>` on the .net side, and then sending only the Id to Rust. In the reverse direction, the Id would be looked up in the dictionary. You'd also need to send a "manage" function to rust for clone/dropping the Id, to clean up the corresponding reference in the dictionary. This is very similar to how delegates are handled at the moment.

3. Originally I wanted to automatically generate other languages (by parsing the C#) using the .net `CodeDOM`, but in practice I found it doesn't support that aspect. I don't really want to end up with N*M implementations where N is the number of supported types and M is the number of languages. If you can find out a way to support other languages without leading to a much larger number of implementations, then that would be great.

**Comment by lenscas** [comment]
> Not at the moment. Currently derive(Net) requires conversion in both directions to work, so it's not possible to omit fields like that, but it's something I may add in future.

So, to allow the .NET to get access to a lua instance I would have to go the global HashMap way? Ok, not the nicest but doable.

> No, although even if you could, the code wouldn't be able to do much beyond send it back. This might not be too hard to add support for if you want to open a PR. It would basically involve storing a Dictionary<Id, object> on the .net side, and then sending only the Id to Rust. In the reverse direction, the Id would be looked up in the dictionary. You'd also need to send a "manage" function to rust for clone/dropping the Id, to clean up the corresponding reference in the dictionary. This is very similar to how delegates are handled at the moment.

ok, not sure how much I will need it (if, at all) but it i good to know that it will have pretty big limitations

> Originally I wanted to automatically generate other languages (by parsing the C#) using the .net CodeDOM, but in practice I found it doesn't support that aspect. I don't really want to end up with N*M implementations where N is the number of supported types and M is the number of languages. If you can find out a way to support other languages without leading to a much larger number of implementations, then that would be great.

yea, ending up with N * M implementations would indeed suck.

**Comment by Diggsey** [comment]
> So, to allow the .NET to get access to a lua instance I would have to go the global HashMap way? Ok, not the nicest but doable.

Not necessarily: the Net traits are implemented for all `Arc<T>`, so you can wrap your lua instance in an `Arc`. On the .net side this comes through as an `IOpaqueHandle`.

**Comment by lenscas** [comment]
oh, that is nice :)

I should be able to use that. Thanks :)
