### ISSUE TITLE
Implement Net, FromNet, ToNet for custom structs

### ISSUE THREAD

**Issue by ItsMeViipeR** [Diggsey/rnet#2]
Hey! I want to use a custom struct with RNet but I don't know how to implement these traits for mine. Can you explain me how to do?

**Comment by ItsMeViipeR** [comment]
My test structs:
```rs
pub struct Evenement {
    pub test: String,
}

pub struct Personne {
    pub name: String,
    pub prenom: String,
    pub evenements: Vec<Evenement>
}
```

**Comment by Diggsey** [comment]
See step (2) from the instructions. Just add `#[derive(Net)]` to your structs - it will implement the necessary traits.
