### ISSUE TITLE
Maintainence Status 

### ISSUE THREAD

**Issue by microhobby** [Diggsey/rnet#4]
Hey @Diggsey , let me know if you still want to continue maintaining this project or if some member of the community could fork it and continue the maintenance.

There are some changes in the newest versions of Rust that need attention https://github.com/slint-ui/slint/pull/3913#issuecomment-1807740358

let me know

**Comment by Diggsey** [comment]
Hi @microhobby , I wasn't aware anyone was actively using rnet - if you would like to assist with maintaining the project I'd be happy to add you.

**Comment by microhobby** [comment]
I would love to help @Diggsey , thanks

**Comment by Diggsey** [comment]
Great, I've sent you an invite.

**Comment by microhobby** [comment]
Hey @Diggsey I committed the fixes and tried to create the `0.3.0` release. But appears that my user does not have access to the secrets (I think). Because the publish action was running for more than 1h, it doesn't seem like a time-consuming task. I think that the login was waiting for input.


https://github.com/Diggsey/rnet/actions/runs/6880055455
https://github.com/Diggsey/rnet/releases/tag/0.3.0

**Comment by microhobby** [comment]
> Hey @Diggsey I committed the fixes and tried to create the `0.3.0` release. But appears that my user does not have access to the secrets (I think). Because the publish action was running for more than 1h, it doesn't seem like a time-consuming task. I think that the login was waiting for input.
> 
> https://github.com/Diggsey/rnet/actions/runs/6880055455 https://github.com/Diggsey/rnet/releases/tag/0.3.0

ok, looking to the `cargo login` command I see that maybe the `--` is not needed anymore, let's see

**Comment by microhobby** [comment]
@Diggsey yeah, the login without the `--` worked! We have the `0.3.0` published!

**Comment by Diggsey** [comment]
Thanks @microhobby, I'll take a look when I have a bit more time :)
